export const ActionTypes = {
  Login: 'LOGIN',
  Register: 'REGISTER',
  SetSoberPlan: 'SET_SOBER_PLAN',
  Logout: 'LOGOUT',
  ShowLoading: 'SHOW_LOADING',
  HideLoading: 'HIDE_LOADING',
  GetTrendingPost: 'GET_TRENDING_POST',
  CreatePost: 'CREATE_POST',
  UsersPost: 'USERS_POSTS',
  MoreUsersPost: 'MORE_USERS_POSTS',
  OthersPost: 'OTHERS_POSTS',
  MoreOthersPost: 'MORE_OTHERS_POSTS',
  LikePost: 'LIKE_POST',
  GetAllComments: 'GET_ALL_COMMENTS',
  GetMoreComments: 'GET_MORE_COMMENTS',
  AddComments: 'ADD_COMMENTS',
  DeleteComment: 'DELETE_COMMENT',
  DeleteMyPost: 'DELETE MY_POST',
  MyPostLikes: 'MY_POST_LIKES',
  GetSoberActivity: 'GET_SOBER_ACTIVITY',
  GetMoreSoberActivity: 'GET_MORE_SOBER_ACTIVITY',
  EmptySoberActivity: 'EMPTY_SOBER_ACTIVITY',
  GetSuicideLinks: 'GET_SUICIDE_LINKS',
  GetForumTopics: 'GET_FORUM_TOPICS',
  GetAllTherapist: 'GET_ALL_THERAPIST',
  GetMoreAllTherapist: 'GET_MORE_ALL_THERAPIST',
  GetRehabs: 'GET_REHABS',
  GetMoreRehabs: 'GET_MORE_REHABS',
  GetPatients: 'GET_PATIENTS',
  GetMorePatients: 'GET_MORE_PATIENTS',
  GetMusic: 'GET_MUSIC',
  GetMoreMusic: 'GET_MORE_MUSIC',
  GetYogaClasses: 'GET_YOGA_CLASSES',
  GetSponseeRehabs: 'GET_SPONSEE_REHABS',
  GetMoreSponseeRehabs: 'GET_MORE_SPONSEE_REHABS',
  GetSponsorEvents: 'GET_SPONSOR_EVENTS',
  GetMoreSponsorEvents: 'GET_MORE_SPONSOR_EVENTS',
  GetPages: 'GET_PAGES',
  Notifications: 'NOTIFICATIONS',
  MoreNotifications: 'MORE_NOTIFICATIONS',
  Update_Profile: 'UPDATE_PROFILE',
  PromoteMyPost: 'PROMOTE_MY_POST',
  GetQuotes: 'GET_QUOTES',
  GetAchievements: 'GET_ACHIEVEMENTS',
  GetMoreAchievements: 'GET_MORE_ACHIEVEMENTS',
  IncreaseSteps: 'INCREASE_STEPS',
  ResetSteps: 'RESET_STEPS',
  GetSteps: "GET_STEPS",
  GetChatList: 'GET_CHAT_LIST',
  GetMoreChatList: 'GET_MORE_CHAT_LIST',
  GetMessages: "GET_MESSAGES",
  GetMoreMessages: "GET_MORE_MESSAGES",
  SendMessages: 'SEND_MESSAGES',
  SendingMessage: 'SENDING_MESSAGE',
  UpdateChatList: "UPDATE_CHATLIST",
  AddSchedule: "ADD_SCHEDULE",
  GetSchedulesDate: 'GET_SCHEDULE_DATE',
  GetSchedules: 'GET_SCHEDULES',
  GetMoreSchedules: 'GET_MORE_SCHEDULES',
  SetPaymentMethods: "SET_PAYMENT_METHODS",
  DeletePaymentMethods: "DELETE_PAYMENT_METHOD",
  SubscribePackage: "SUBSCRIBE_PACKAGE",
  DefaultPaymentMethods: "DEFAULT_PAYMENT_METHOD",
  ChatNotify: "CHAT_NOTIFY",
  GetMeeting: "GET_MEETING",
  GetMoreMeeting: "GET_MORE_MEETING",
  DeleteMeeting: "DELETE_MEETING",
  DeleteSoberActivity: "DELETE_SOBER_ACTIVITY",
  DeleteClass: "DELETE_CLASS",
  TRACK_STEPS:"TRACK_STEPS"
  // GetExercises: "GET_EXERCISES",
  // GetReading: "GET_READING",
  // GetPlaying: "GET_PLAYING",
  // GetLearning: "GET_LEARNING",
  // GetCooking: "GET_COOKING",
  // GetMoreExercises: "GET_MORE_EXERCISES",
  // GetMoreReading: "GET_MORE_READING",
  // GetMorePlaying: "GET_MORE_PLAYING",
  // GetMoreLearning: "GET_MORE_LEARNING",
  // GetMoreCooking: "GET_MORE_COOKING"
};
