//export const base_url = 'http://192.168.0.171/drytime/drytime7.4/api/';
export const base_url = 'https://drytimeapp.com/drytime7.4/api/';
//export const base_url = 'http://202.142.180.146:90/drytime/api';
//export const base_url = 'https://healthconet.com/drytimeapp/drytime7.4/api/';
//export const img_url = 'http://192.168.0.171/drytime/public/images/';
//export const img_url = 'http://202.142.180.146:90/drytime/public/images/';
export const img_url = 'https://drytimeapp.com/public/images/';
//export const img_url = 'https://healthconet.com/drytimeapp/public/images/';
export const APIs = {
  REGISTER: `register`,
  LOGIN: `login`,
  DELETE_ACCOUNT:"deleteAccount",
  SOCIAL_LOGIN: 'userInfo',
  UPDATE_PROFILE: "updateProfile",
  GET_TRENDING: 'postTrending',
  CREATE_POST: "createPost",
  GET_USER_POSTS: "allUserPosts",
  GET_OTHERS_POSTS: "allPosts",
  LIKE_POST: "postLike",
  GET_ALL_COMMENTS: "getAllComments",
  ADD_COMMENT: "postComment",
  DELETE_COMMENTS: "postCommentDelete",
  DELETE_POST: "deletePost",
  GET_ALL_LIKES: "getAllPostLikes",
  GET_SOBER_ACTIVITY: "getSoberActivity",
  GET_SUICIDE_LINKS: "getLinks",
  GET_FORUM_TOPICS: "getForumTopics",
  GET_ALL_THERAPISTS: "getAllTherapistData",
  ADD_THERAPIST_REQUEST: "scheduleTherapist",
  GET_REHABS: "getRehabsList",
  GET_PATIENTS: "getPatientByRehab",
  GET_MUSIC: "getMusicList",
  EDIT_POST: "updatePost",
  GET_YOGA_CLASSES: "yogaClassList",
  GET_SPONSEE_REHABS: "getRehabBySponsee",
  GET_SPONSOR_EVENTS: "getAllEvents",
  ADD_SPONSOR_REQUEST: "storeNotes",
  RATE_APP: "storeRating",
  GET_PAGES: "about",
  CONTACT_US: "storeContact",
  NOTIFICATION: "notifications",
  GET_ONLY_REHABS: "getRehabs",
  PROMOTE_POST: "updatePostStatus",
  GET_QUOTES: 'getQuotes',
  SET_PLAN: "storeSchedule",
  GET_ACHIEVEMENTS: "userAchievements",
  ADD_SPONSOR: 'storeSponsor',
  ADD_SPONSEE: 'storeSponsee',
  STORE_STEPS: 'stepsStore',
  GET_STEPS: "getStepsByDay",
  GET_CHATS: 'chatIndex',
  GET_MESSAGES: 'viewChatlist',
  SEND_MESSAGE: 'sendMessage',
  SEND_EMAIL: "sendMail",
  RESET_PASSWORD: "resetPassword",
  ADD_SCHEDULE: "scheduleSoberActivity",
  ADD_SCHEDULE_MEAL: "storeMealSchedule",
  GET_SCHEDULES: "getActivityByDates",
  GET_SCHEDULED_DATES: 'getAllScheduleDates',
  GET_SINGLE_POST: "getSinglePost",
  GET_PAYMENT_METHODS: "showMethod",
  ADD_PAYMENT_METHOD: "storeCard",
  DELETE_PAYMENT_METHOD: "deleteCard",
  DEFAULT_PAYMENT_METHOD: "updateDefaultCard",
  GET_SUBSCRIPTIONS: "getAllPackages",
  SUBSCRIBE_PACKAGE: "subscribe",
  GET_USERS: "getUsers",
  GET_MEETINGS: "getMeeting",
  CREATE_MEETING: "createMeeting",
  DELETE_MEETING: "deleteMeeting",
  AWARD_TOKEN: "sendToken",
  ADD_ACTIVITY_VIDEO: "userVideo",
  ADD_CLASS_VIDEO: "storeYogaClass",
  DELETE_SOBER_ACTIVITY: "deleteSoberActivity",
  DELETE_CLASS: "deleteYogaClasses",
  GENERATE_JWT: "getJWT"
  // GET_EXERCISES: "getExercise",
  // GET_INSTRUMENT: "getInstrument",
  // GET_PLAYING: "getPlaying",
  // GET_COOKING: "getCooking",
  // GET_READING: "getReading"
};
